name: "ğŸ§ Checking IR Files"

on:
  pull_request:
    paths:
      - '**/*.ir'

jobs:
  lint:
    name: "ğŸ› Looking for issues"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Clean Script Directory
        run: rm -rf fff-ir-lint
      
      - uses: actions/checkout@v4
        with:
          repository: 'darmiel/fff-ir-lint'
          path: fff-ir-lint
      
      # Get changed files
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: "**/*.ir"
          json: true
          write_output_files: true
          sha: ${{ github.event.pull_request.head.sha }}
          
      - name: Verify the contents of the .github/outputs/added_files.json file
        run: cat .github/outputs/added_files.json
